<header>
    <nav>
        <img src="images/favicon.png" alt="Pets Victoria Logo" class="logo">
        <div class="dropdown">
            <button onclick="navDrop()" class="dropbtn">Select an Option</button>
            <div id="Dropnav" class="dropdown-content">
                <a href="index.php">Home</a>
                <a href="pets.php">Pets</a>
                <a href="add.php">Add More</a>
                <a href="gallery.php">Gallery</a>
            </div>
        </div>

        <form>
            <input type="text" placeholder="Search...">
            <button type="submit">🔍</button>
        </form>
    </nav>
</header>
