<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pets Victoria - Home</title>
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Permanent+Marker&family=Ysabeau+SC&family=Poetsen+One&display=swap">
</head>
<body>
    <div class="lineup"></div>
